import { createRequestHandler, type ServerBuild } from 'react-router';

// eslint-disable-next-line no-restricted-imports -- `~/` alias only reaches `app/`
import { buildCsp } from '../app/utils/csp';
// The imports below reach outside `app/`, so they can't use the `~/`
// alias. `build/server` is generated by `react-router build` and
// gitignored, so tsc + eslint don't see it until after a build.
// eslint-disable-next-line no-restricted-imports -- `~/` alias only reaches `app/`
import { createAppLoadContext } from '../app/utils/load-context';
// eslint-disable-next-line no-restricted-imports -- `~/` alias only reaches `app/`
import { isOverLimit } from '../app/utils/rate-limit';
// eslint-disable-next-line no-restricted-imports -- `~/` alias only reaches `app/`
import { getTurnstileConfig } from '../app/utils/turnstile';
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - build/server/index.js is generated by `react-router build`
// eslint-disable-next-line no-restricted-imports, import/no-unresolved -- generated at build time
import * as build from '../build/server';

// Cloudflare Workers entrypoint. See docs/security.md for the CSP,
// rate-limit, and private-cache posture this file enforces.
const STATIC_PREFIXES = ['/assets/', '/fonts/', '/.well-known/'];
const STATIC_EXACT = new Set(['/favicon.ico', '/robots.txt', '/sitemap.xml']);

const requestHandler = createRequestHandler(build as unknown as ServerBuild);

// 128 bits of entropy in url-safe base64 (16 random bytes → 22 chars).
function mintNonce(): string {
  const bytes = new Uint8Array(16);
  crypto.getRandomValues(bytes);
  return btoa(String.fromCharCode(...bytes))
    .replaceAll('+', '-')
    .replaceAll('/', '_')
    .replaceAll('=', '');
}

// Static assets carry no inline scripts, so they get the nonce-less policy.
const STATIC_CSP = buildCsp('');

const STATIC_SECURITY_HEADERS: Record<string, string> = {
  'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'DENY',
  'Referrer-Policy': 'strict-origin-when-cross-origin',
  'Permissions-Policy':
    'camera=(), microphone=(), geolocation=(), interest-cohort=(), payment=(), usb=(), magnetometer=(), gyroscope=(), accelerometer=()',
};

// See docs/security.md § "SSR HTML is Cache-Control: private". Also
// strip `s-maxage` / `proxy-revalidate` — those directives are for
// shared caches and would let a non-conforming intermediary hold the
// nonced HTML despite `private`.
function privatizeCacheControl(headers: Headers): void {
  const cc = headers.get('Cache-Control');
  if (!cc) return;
  const scrubbed = cc
    .split(',')
    .map((d) => d.trim())
    .filter((d) => !/^(s-maxage|proxy-revalidate)\b/i.test(d))
    .map((d) => (/^public\b/i.test(d) ? 'private' : d))
    .join(', ');
  if (scrubbed !== cc) headers.set('Cache-Control', scrubbed);
}

function withSecurityHeaders(
  response: Response,
  csp: string,
  extra?: Record<string, string>,
  isHtml = false
): Response {
  const headers = new Headers(response.headers);
  for (const [k, v] of Object.entries(STATIC_SECURITY_HEADERS)) headers.set(k, v);
  headers.set('Content-Security-Policy', csp);
  if (isHtml) privatizeCacheControl(headers);
  if (extra) for (const [k, v] of Object.entries(extra)) headers.set(k, v);
  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}

const DATA_RATE_LIMIT_PER_HOUR = 60;
// A real visitor downloads the CV once or twice (the hover-prefetch
// plus the click can count as two requests). 60 leaves generous room
// for several recruiters behind one office NAT while still cutting off
// a single-address download loop.
const PDF_RATE_LIMIT_PER_HOUR = 60;

const clientIp = (request: Request): string =>
  request.headers.get('CF-Connecting-IP') ?? 'local-dev';

// PDFs live under /assets/files/ (the CV and certificate PDFs). They
// carry contact details, so they're worth a per-IP cap that ordinary
// static assets (hashed JS/CSS, fonts) don't need.
const isPdfDownload = (pathname: string): boolean =>
  pathname.startsWith('/assets/files/') && pathname.toLowerCase().endsWith('.pdf');

// Match all four browser-set signals so a scraper has to spoof each
// one to bypass the .data cap. See docs/security.md § ".data rate
// limit".
function isTrustedInternalNav(request: Request, origin: string): boolean {
  const site = request.headers.get('Sec-Fetch-Site');
  const dest = request.headers.get('Sec-Fetch-Dest');
  const mode = request.headers.get('Sec-Fetch-Mode');
  if (site !== 'same-origin' || dest !== 'empty' || mode !== 'cors') return false;
  const referer = request.headers.get('Referer');
  if (!referer) return false;
  try {
    return new URL(referer).origin === origin;
  } catch {
    return false;
  }
}

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);

    // Static assets carry no inline scripts, so they get the nonce-less
    // CSP and skip the mint entirely.
    if (STATIC_EXACT.has(url.pathname) || STATIC_PREFIXES.some((p) => url.pathname.startsWith(p))) {
      if (
        isPdfDownload(url.pathname) &&
        (await isOverLimit({
          kv: env.RATELIMIT_KV,
          ctx,
          purpose: 'pdf',
          ip: clientIp(request),
          limit: PDF_RATE_LIMIT_PER_HOUR,
        }))
      ) {
        return withSecurityHeaders(new Response('Too Many Requests', { status: 429 }), STATIC_CSP, {
          'Retry-After': '3600',
        });
      }
      return withSecurityHeaders(await env.ASSETS.fetch(request), STATIC_CSP);
    }

    const nonce = mintNonce();
    // The Turnstile origins are only allowed once a site key is
    // configured, so a deploy without one keeps the strict policy.
    const csp = buildCsp(nonce, { turnstile: getTurnstileConfig(env).enabled });

    if (url.pathname.endsWith('.data')) {
      if (
        !isTrustedInternalNav(request, url.origin) &&
        (await isOverLimit({
          kv: env.RATELIMIT_KV,
          ctx,
          purpose: 'data',
          ip: clientIp(request),
          limit: DATA_RATE_LIMIT_PER_HOUR,
        }))
      ) {
        return withSecurityHeaders(new Response('Too Many Requests', { status: 429 }), csp, {
          'Retry-After': '3600',
          'X-Robots-Tag': 'noindex',
        });
      }
      const context = createAppLoadContext({ env, ctx }, nonce);
      const response = await requestHandler(request, context);
      // Merge `X-Robots-Tag: noindex` in the same header pass as the
      // rest of the security headers — avoids a second Response wrap.
      return withSecurityHeaders(response, csp, { 'X-Robots-Tag': 'noindex' });
    }
    const context = createAppLoadContext({ env, ctx }, nonce);
    return withSecurityHeaders(await requestHandler(request, context), csp, undefined, true);
  },
} satisfies ExportedHandler<Env>;
